### ISSUE TITLE
Compatibility with Graylog and ES 2.x

### ISSUE THREAD

**Issue by bonzi316** [sivasamyk/graylog-plugin-input-jmx#3]
Hi,

your pluging is creating field with dots in ES.  In ES 2.x field with dots are no longer supported.  We have a fix to reindex the data with logstash, but it seems that your plugin will no longer be comptabile with Graylog 2.x since it only support ES 2.x.

Do you have a plan to fix this behavior ?

Thanks

**Comment by sivasamyk** [comment]
Yes. Will fix

**Comment by sivasamyk** [comment]
fixed
