### ISSUE TITLE
How to monitor Tomcat log

### ISSUE THREAD

**Issue by vanhung89** [sivasamyk/graylog-plugin-input-jmx#4]
I need to moniror Tomcat log, can you help me configure? If you have an example, I will be easy to confiure. Thanks

**Comment by sivasamyk** [comment]
You can configure tomcat to use Log4J and add GELF Log4J appender from https://github.com/Graylog2/log4j2-gelf

Steps to configure log4j in tomcat can be found @ https://tomcat.apache.org/tomcat-6.0-doc/logging.html#Using_Log4j
