### ISSUE TITLE
how to monitor in docker?

### ISSUE THREAD

**Issue by linkght-inject** [sivasamyk/graylog-plugin-input-jmx#6]
I run a java programe in docker with command:
`java \
-Dcom.sun.management.jmxremote \
-Dcom.sun.management.jmxremote.port=12345 \
-Dcom.sun.management.jmxremote.authenticate=false \
-Dcom.sun.management.jmxremote.ssl=false \
-jar /root/graylog/log-demo.jar`

and the confiuration in graylog:
`configCustomFilePath: <empty>
configHosts: 192.168.10.17
configInterval: 1
configIntervalUnit: SECONDS
configLabel: java
configPassword: ********
configPort: 12345
configType: jvm.json
configUsername: <empty>
decompress_size_limit: 8388608
override_source: <empty>`

but i cannot get the log with graylog.can you help me?

**Comment by sivasamyk** [comment]
@finalshrey Hope you have figured this out. If yes, I will close this.
